name: gleap_dio_interceptor
description: A Dio Interceptor for Gleap
version: 1.2.3
homepage: https://gleap.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.3
  flutter:
    sdk: flutter
  gleap_sdk:
    git:
      url: https://github.com/GleapSDK/Flutter-SDK.git
      ref: flutter-v2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
